
theta = 0;
Yab=transform(theta, 'qR', 'YAB', 1);
axisRanges=round(Yab.range*Yab.discreteRange);
axisLengths=round(Yab.axisLength*Yab.discreteRange);
individualName={'FSkin', 'JSkin', 'NSkin'};
digitName={'Hands', 'Index_Pad', 'Little_Pad', 'Middle_Pad', 'Ring_Pad', 'Thumb_Pad', ...
                    'Index_Tip', 'Little_Tip', 'Middle_Tip', 'Ring_Tip', 'Thumb_Tip'};
dirName = { 'Skin/IndividualSkin/FSkin/Hands/Orig/', ...
    'Skin/IndividualSkin/FSkin/Index/Pad/Orig/','Skin/IndividualSkin/FSkin/Little/Pad/Orig/', 'Skin/IndividualSkin/FSkin/Middle/Pad/Orig/', ...
    'Skin/IndividualSkin/FSkin/Ring/Pad/Orig/', 'Skin/IndividualSkin/FSkin/Thumb/Pad/Orig/', ...
    'Skin/IndividualSkin/FSkin/Index/Tip/Orig/','Skin/IndividualSkin/FSkin/Little/Tip/Orig/', 'Skin/IndividualSkin/FSkin/Middle/Tip/Orig/', ...
    'Skin/IndividualSkin/FSkin/Ring/Tip/Orig/', 'Skin/IndividualSkin/FSkin/Thumb/Tip/Orig/'; ...
    'Skin/IndividualSkin/JSkin/Hands/Orig/Orig/', ...
    'Skin/IndividualSkin/JSkin/Index/Pad/Orig/','Skin/IndividualSkin/JSkin/Little/Pad/Orig/', 'Skin/IndividualSkin/JSkin/Middle/Pad/Orig/', ...
    'Skin/IndividualSkin/JSkin/Ring/Pad/Orig/', 'Skin/IndividualSkin/JSkin/Thumb/Pad/Orig/', ...
    'Skin/IndividualSkin/JSkin/Index/Tip/Orig/','Skin/IndividualSkin/JSkin/Little/Tip/Orig/', 'Skin/IndividualSkin/JSkin/Middle/Tip/Orig/', ...
    'Skin/IndividualSkin/JSkin/Ring/Tip/Orig/', 'Skin/IndividualSkin/JSkin/Thumb/Tip/Orig/'; ...
    'Skin/IndividualSkin/NSkin/Hands/Orig/Orig/', ...
    'Skin/IndividualSkin/NSkin/Index/Pad/Orig/','Skin/IndividualSkin/NSkin/Little/Pad/Orig/', 'Skin/IndividualSkin/NSkin/Middle/Pad/Orig/', ...
    'Skin/IndividualSkin/NSkin/Ring/Pad/Orig/', 'Skin/IndividualSkin/NSkin/Thumb/Pad/Orig/', ...
    'Skin/IndividualSkin/NSkin/Index/Tip/Orig/','Skin/IndividualSkin/NSkin/Little/Tip/Orig/', 'Skin/IndividualSkin/NSkin/Middle/Tip/Orig/', ...
    'Skin/IndividualSkin/NSkin/Ring/Tip/Orig/', 'Skin/IndividualSkin/NSkin/Thumb/Tip/Orig/';};
for i=1:3
    for j=3:11
        disp(strcat('Processing :  ',individualName{i},'__', digitName{j}));
        disp(dir(strcat(dirName{i,j},'*.jpg')));
        createBinsFromDir(dirName{i,j}, individualName{i}, digitName{j},Yab)
    end
end

